'use client';
import {useState} from 'react';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {Flame,Menu,X,ShoppingBag,ArrowUpRight,Plus,Check} from 'lucide-react';
import {motion,useReducedMotion} from 'framer-motion';
import {useBag} from '@/components/store-provider';
import {type Burger,money} from '@/lib/menu';
export function Brand(){return <Link className="brand" href="/" aria-label="Ember and Bun home"><Flame aria-hidden="true" className="brand-flame" fill="currentColor"/><span>ember<span className="amp">&</span>bun<small>SMASHED. SEARED. SERVED.</small></span></Link>;}
export function Header(){const path=usePathname();const [open,setOpen]=useState(false);const {count,showBag}=useBag();return <div className="site-shell nav-shell"><a className="skip-link" href="#main-content">Skip to content</a><header className="header"><Brand/><nav className="pill-nav" aria-label="Main navigation"><Link className={path==='/'?'active':''} aria-current={path==='/'?'page':undefined} href="/">Home</Link><Link className={path==='/shop'?'active':''} aria-current={path==='/shop'?'page':undefined} href="/shop">Shop burgers</Link><Link href="/#story">Our story <ArrowUpRight size={14}/></Link></nav><div className="header-tools"><button className="nav-order bag-toggle" onClick={showBag} aria-label={`Open bag, ${count} items`}><span>Your bag</span><ShoppingBag size={19}/><span className="bag-count" aria-live="polite">{count}</span></button><button className="mobile-toggle" aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<nav className="mobile-nav" aria-label="Mobile navigation"><Link href="/" onClick={()=>setOpen(false)}>Home <ArrowUpRight/></Link><Link href="/shop" onClick={()=>setOpen(false)}>Shop burgers <ArrowUpRight/></Link><Link href="/#story" onClick={()=>setOpen(false)}>Our story <ArrowUpRight/></Link></nav>}</header></div>;}
export function Footer(){return <footer className="footer"><div className="footer-top"><div><Brand/><p>A little fire. A lot of flavour.</p></div><nav aria-label="Footer navigation"><Link href="/shop">Shop burgers <ArrowUpRight size={16}/></Link><Link href="/#story">Our story <ArrowUpRight size={16}/></Link><Link href="/#recipe">The good stuff <ArrowUpRight size={16}/></Link><Link href="/#questions">Good questions <ArrowUpRight size={16}/></Link><Link href="/orders" className="staff-link">Staff board <ArrowUpRight size={16}/></Link></nav></div><div className="footer-wordmark" aria-hidden="true">STAY HUNGRY<span>®</span></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Ember & Bun.</span><span>SMASHED. SEARED. SERVED.</span><a href="#top">Back to top ↑</a></div></footer>;}
export function ProductCard({burger,index=0}:{burger:Burger;index?:number}){const {add,bag}=useBag();const [added,setAdded]=useState(false);const reduce=useReducedMotion();function addBurger(){add(burger.id);setAdded(true);}return <motion.article className={`menu-card ${burger.color}`} initial={reduce?false:{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:.45,delay:index*.07}}><div className="menu-card-art"><span className="menu-card-label">{burger.label}</span><img src={burger.image} alt={burger.name} width={480} height={480} loading="lazy"/><span className="category-badge">{burger.category}</span></div><div className="menu-card-body"><div className="menu-card-title"><h3>{burger.name}</h3><span>{money(burger.price)}</span></div><p>{burger.description}</p><div className="menu-card-bottom"><span>{burger.category==='Chicken'?'A little heat':burger.category==='Veggie'?'Vegetarian':'Double beef'}</span><button className="add-burger" disabled={(bag[burger.id]||0)>=20} onClick={addBurger} aria-label={`Add ${burger.name} to bag`}>{added?<Check size={19}/>:<Plus size={19}/>}<span>{(bag[burger.id]||0)>=20?'Bag limit':added?'Add another':'Add to bag'}</span></button></div></div></motion.article>;}
