'use client';
import Link from 'next/link';
import {ArrowUpRight,Flame,ArrowRight} from 'lucide-react';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {ProductCard} from '@/components/brand-site';
import {burgers} from '@/lib/menu';
export default function LandingSections(){return <>
 <div className="flavour-strip" aria-label="Crispy edges, melty middles, good times"><span>CRISPY EDGES</span><Flame fill="currentColor"/><span>MELTY MIDDLES</span><Flame fill="currentColor"/><span>GOOD TIMES</span><Flame fill="currentColor"/></div>
 <section className="section featured" id="burgers" aria-labelledby="featured-title"><div className="section-heading"><div><span className="section-kicker">01 / THE LINE-UP</span><h2 id="featured-title">PICK YOUR<br/><span className="orange-text">OBSESSION.</span></h2></div><div className="section-intro"><p>Three very good reasons to cancel<br/>your dinner plans.</p><Link href="/shop" className="text-link">Shop all burgers <ArrowUpRight/></Link></div></div><div className="burger-grid">{burgers.map((burger,index)=><ProductCard key={burger.id} burger={burger} index={index}/>)}</div></section>
 <section className="story-section" id="story" aria-labelledby="story-title"><div className="story-copy"><span className="section-kicker">02 / A LITTLE FIRE IN OUR BELLY</span><h2 id="story-title">GOOD BURGERS.<br/>BAD AT<br/><span>COMPROMISE.</span></h2><p>Ember & Bun is built around a simple obsession: that first bite. The crisp edge of a smashed patty. Cheese melting into every corner. Sauce you’ll definitely need another napkin for.</p><p>No towering menus. No overthinking it. Just a small line-up, a hot griddle, and a very good bun.</p><Link href="/shop" className="text-link">Find your first bite <ArrowUpRight/></Link></div><div className="story-art"><span className="story-stamp">LESS FUSS.<br/>MORE FLAVOUR.</span><img src="/smash-burger.png" alt="A closer look at the Ember Double’s melted cheese and crispy beef edges" width={750} height={750} loading="lazy"/><span className="story-caption">THE EMBER DOUBLE / OUR ORIGINAL OBSESSION</span></div></section>
 <section className="section recipe-section" id="recipe" aria-labelledby="recipe-title"><div className="section-heading"><div><span className="section-kicker">03 / IT’S WHAT’S INSIDE</span><h2 id="recipe-title">NOTHING TO HIDE.<br/><span className="outline-text">EVERYTHING TO LOVE.</span></h2></div><p className="recipe-intro">Great burgers don’t need a secret.<br/>They need the good stuff.</p></div><div className="recipe-rows">{[['01','THE CRISPY EDGE.','Smashed thin on a hot griddle. That deeply seared crust is where the flavour starts.'],['02','THE MELTY MIDDLE.','Cheese over the patty while it’s hot. Every layer gets its fair share.'],['03','THE LITTLE KICK.','Sharp pickles, fresh onion and our tangy Ember sauce. The balance to all that richness.'],['04','THE SOFT LANDING.','A toasted sesame brioche that holds the good stuff together. Until the very last bite.']].map(([n,title,copy])=><article className="recipe-row" key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p><ArrowUpRight aria-hidden="true"/></article>)}</div></section>
 <section className="questions-section" id="questions" aria-labelledby="questions-title"><div><span className="section-kicker">04 / BEFORE YOU BITE</span><h2 id="questions-title">GOOD<br/>QUESTIONS.</h2><p>A few things worth knowing<br/>before you get your hands messy.</p></div><Accordion className="faq-list"><AccordionItem value="smash"><AccordionTrigger>What makes a smash burger different?</AccordionTrigger><AccordionContent>A beef patty is pressed onto a very hot griddle, creating a thin, deeply browned crust with crisp edges. Our Ember Double stacks two of them with melted American cheese.</AccordionContent></AccordionItem><AccordionItem value="veggie"><AccordionTrigger>Is there a vegetarian burger?</AccordionTrigger><AccordionContent>Yes. Shroom Service swaps beef for a seared portobello mushroom, with Swiss cheese, caramelised onion, rocket and garlic mayo. It contains dairy and egg, so it isn’t vegan.</AccordionContent></AccordionItem><AccordionItem value="allergens"><AccordionTrigger>Where can I check the ingredients?</AccordionTrigger><AccordionContent>The shop has an ingredients and allergens guide for every burger. The concept menu may change; confirm ingredients and cross-contact information with the restaurant before ordering if you have a food allergy.</AccordionContent></AccordionItem><AccordionItem value="ordering"><AccordionTrigger>Can I place an order online?</AccordionTrigger><AccordionContent>You can explore the menu and build a bag. This is currently a shop preview with sample prices. Checkout, payments, delivery and collection are not connected yet.</AccordionContent></AccordionItem></Accordion></section>
 <section className="closing-cta" aria-labelledby="closing-title"><span className="section-kicker">THAT’S ENOUGH SCROLLING.</span><h2 id="closing-title">YOU HAD US<br/>AT <span>HUNGRY.</span></h2><Link href="/shop" className="cta cta-dark">Let’s fix that <ArrowUpRight/></Link><Flame className="closing-flame" size={210} strokeWidth={1} aria-hidden="true"/></section>
 </>;}
